"""Post summaries and images

Revision ID: 0eb2e40c65b9
Revises: 3ec810e3d423
Create Date: 2025-08-03 17:40:19.452032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb2e40c65b9'
down_revision = '3ec810e3d423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_players_token'), ['token'], unique=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_posts_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_timestamp'))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('image')
        batch_op.drop_column('body')
        batch_op.drop_column('summary')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_token'))
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
